ALTER TABLE orcamentos
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS telegram_message_id INTEGER,
  ADD COLUMN IF NOT EXISTS crm_deal_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS subtotal_equip REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subtotal_servicos REAL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS data VARCHAR(50);

ALTER TABLE planos
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
